achievements = {
    'JANKEN_WIN_1': {'bit': 0b1 << 10, 'name': '初めての勝利',
                     'description': '誰にでも初めてはある！ここからがキミのスタートだ！', 'requirement': 'じゃんけんで1回勝利する。'},
    'JANKEN_WIN_10': {'bit': 0b1 << 11, 'name': '戦いの味',
                      'description': '戦いとは本能。この運命は、まだ始まったばかりなのだ。', 'requirement': 'じゃんけんで10回勝利する。'},
    'JANKEN_WIN_50': {'bit': 0b1 << 12, 'name': '大きな手',
                      'description': '成長はその姿形にさえ影響を及ぼすものだ。', 'requirement': 'じゃんけんで50回勝利する。'},
    'JANKEN_WIN_100': {'bit': 0b1 << 13, 'name': '選ばれし存在',
                       'description': 'そろそろじゃんけんのプロを名乗っても良い。', 'requirement': 'じゃんけんで100回勝利する。'},
    'JANKEN_WIN_200': {'bit': 0b1 << 14, 'name': '英傑の手',
                       'description': 'あいつが持つのは伝説の拳。じゃん拳だ！', 'requirement': 'じゃんけんで200回勝利する。'},
    'JANKEN_WIN_500': {'bit': 0b1 << 15, 'name': 'バーサーカー',
                       'description': '誰かやつを止めてくれ！', 'requirement': 'じゃんけんで500回勝利する。'},
    'JANKEN_WIN_1000': {'bit': 0b1 << 16, 'name': 'ゴッドハンド',
                        'description': '君に叶うやつはもういない。そう、運すらもね。', 'requirement': 'じゃんけんで1000回勝利する。'},
    'JANKEN_LOSE_1': {'bit': 0b1 << 17, 'name': '敗北の味',
                      'description': '', 'requirement': 'じゃんけんで1回敗北する。'},
    'JANKEN_LOSE_10': {'bit': 0b1 << 18, 'name': '戦いの味',
                       'description': '戦いとは本能。この運命は、まだ始まったばかりなのだ。', 'requirement': 'じゃんけんで10回敗北する。'},
    'JANKEN_LOSE_50': {'bit': 0b1 << 19, 'name': '大きな手',
                       'description': '成長はその姿形にさえ影響を及ぼすものだ。', 'requirement': 'じゃんけんで50回敗北する。'},
    'JANKEN_LOSE_100': {'bit': 0b1 << 20, 'name': '選ばれし存在',
                        'description': 'そろそろじゃんけんのプロを名乗っても良い。', 'requirement': 'じゃんけんで100回敗北する。'},
    'JANKEN_LOSE_200': {'bit': 0b1 << 21, 'name': '英傑の手',
                        'description': 'あいつが持つのは伝説の拳。じゃん拳だ！', 'requirement': 'じゃんけんで200回敗北する。'},
    'JANKEN_LOSE_500': {'bit': 0b1 << 22, 'name': 'バーサーカー',
                        'description': '誰かやつを止めてくれ！', 'requirement': 'じゃんけんで500回敗北する。'},
    'JANKEN_LOSE_1000': {'bit': 0b1 << 23, 'name': 'ゴッドハンド',
                         'description': '君に叶うやつはもういない。そう、運すらもね。', 'requirement': 'じゃんけんで1000回敗北する。'}
}
