version: "3.8"
services:
  labomen-bot-dev:
    build: ./
    tty: true
    working_dir: /usr/local/labomen-bot/
    container_name: labomen-bot-dev
    volumes:
      - ..:/usr/local/labomen-bot:delegated
      - ~/.ssh:/root/.ssh:delegated,ro
