name: Deploy to Server
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      USER: ${{ secrets.SERVER_USER }}
      HOST: ${{ secrets.SERVER_HOST }}
    steps:
      - name: deploy
        run: echo "$SSH_KEY" > ssh_key && chmod 600 ssh_key &&
          ssh -o StrictHostKeyChecking=no -i ssh_key ${USER}@${HOST} '
          cd /home/ubuntu/labomen-bot &&
          sudo docker-compose down &&
          git checkout master &&
          git pull &&
          echo ${{ github.sha }} > .version &&
          sudo docker-compose up -d
          '
          && exit
