name: Deploy to EC2
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
    steps:
      - name: deploy
        run: echo "$SECRET_KEY" > secret_key && chmod 600 secret_key &&
          ssh -o StrictHostKeyChecking=no -i secret_key ${EC2_USER}@${EC2_HOST} '
          cd /home/ubuntu/labomen-bot &&
          sudo docker-compose down &&
          git checkout master &&
          git pull &&
          sudo docker-compose up
          '
          && exit
