name: Deploy to EC2
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
    steps:
      - name: deploy
        run: echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/Repo/labomen-bot && git pull && pip3 install -r requirements.txt && screen -S labomen-bot -X quit && screen -S labomen-bot python3 main.py"
