name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISCORD_ACCESS_TOKEN: ${{ secrets.DISCORD_ACCESS_TOKEN }}
      DISCORD_CHANNEL_IDS: ${{ secrets.DISCORD_CHANNEL_IDS }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
          pipenv install -r ./requirements.txt
      - name: Run test
        run: |
          pipenv run python main.py
