name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISCORD_ACCESS_TOKEN: ${{ secrets.DISCORD_ACCESS_TOKEN }}
      DISCORD_CHANNEL_IDS: ${{ secrets.DISCORD_CHANNEL_IDS }}

    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
